language: node_js

install:
  - npm install grunt-cli -g

script:
  - grunt build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
